marvel_app/authentication/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from marvel_app.forms import UserSignUpForm, UserLoginForm
from marvel_app.models import User, db, check_password_hash
from flask_login import login_user, logout_user, login_required

# Creating blueprint for authorization routes
auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserSignUpForm()
    if request.method == 'POST' and form.validate_on_submit():
        first_name = form.first_name.data
        last_name = form.last_name.data
        username = form.username.data
        email = form.email.data
        password = form.password.data
        confirm = form.confirm.data
        print([first_name,last_name,username,email,password,confirm])
        new_user = User(first_name, last_name, username, email, password)
        db.session.add(new_user)
        db.session.commit()
        flash(f'You have successfully created a user account {username}', 'user_created')
        return redirect(url_for('auth.signin'))
    return render_template('signup.html', form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        print([username, password])
        logged_user = User.query.filter(User.username == username).first()
        if logged_user and check_password_hash(logged_user.password, password):
            login_user(logged_user)
            flash(f'Successfully logged in as: {username}', 'auth_success')
            return redirect(url_for('site.home'))
        else:
            flash('Email or password is incorrect, please try again', 'auth_failed')
            return redirect(url_for('auth.signin'))
    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash(f'Successfully logged out of account', 'logout_success')
    return redirect(url_for('auth.signin'))

marvel_app/site/routes.py
from marvel_app.models import Character, db
from marvel_app.forms import CreateCharacter
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user

# Creating blueprint for site routes
site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    owner = current_user.token
    characters = Character.query.filter_by(user_token = owner).all()
    return render_template('profile.html', characters = characters)

@site.route('/create', methods = ['GET', 'POST'])
@login_required
def create():
    form  = CreateCharacter()
    if request.method == 'POST' and form.validate_on_submit():
        name = form.name.data
        description = form.description.data
        movies = form.movies.data
        events = form.events.data
        series = form.series.data
        powers = form.powers.data
        snapped = form.snapped.data
        user_token = current_user.token
        character = Character(name, description, movies, events, series, powers, snapped, user_token)
        db.session.add(character)
        db.session.commit()
        return redirect(url_for('site.profile'))
    return render_template('create.html', form = form)

marvel_app/templates/auth_login.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset>
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Please enter username...") }}
        </fieldset>
        <fieldset>
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Please enter password...") }}
        </fieldset>
        <div id="sub_butt">
            {{ form.submit_button(class = "btn btn-danger") }}
        </div>
    </div>
</form>

marvel_app/templates/auth_register.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset>
            {{ form.first_name.label }}
            {{ form.first_name(class = "form-control", placeholder = "Please enter your first name...") }}
        </fieldset>
        <fieldset>
            {{ form.last_name.label }}
            {{ form.last_name(class = "form-control", placeholder = "Please enter your last name...") }}
        </fieldset>
        <fieldset>
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Please enter a user name...") }}
        </fieldset>
        <fieldset>
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Please enter your email...") }}
        </fieldset>
        <fieldset>
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Please enter a password...") }}
        </fieldset>
        <fieldset>
            {{ form.confirm.label }}
            {{ form.confirm(class = "form-control", placeholder = "Please confirm your password...") }}
        </fieldset>
        <div id="sub_butt">
            {{ form.submit_button(class = "btn btn-danger") }}
        </div>
        
    </div>
</form>

marvel_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="Description" content="Enter your description here"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <link rel="stylesheet" href="../static/css/main.css">
        <link rel="shortcut icon" href="../static/images/favicon.png">
        <title>Mavel DB</title>
    </head>
    <body>
        <!-- Navbar creation -->
        <nav class="navbar navbar-light bg-danger fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('site.home')}}">
                    <img src="../static/images/favicon.png" alt="" width="30" height="24" class="d-inline-block align-text-top"><span class="logo">arvel</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"                 data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel"><img src="../static/images/favicon.png" alt="" width="30" height="24" class="d-inline-block align-text-top"><span class="text-black">arvel</span></h5>
                        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{{ url_for('site.home')}}">Home</a>
                            </li>
                            {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('site.profile')}}">Account</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('site.create')}}">Upload</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.logout')}}">Log Out</a>
                            </li>
                            {% else %} 
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.signin')}}">Sign In</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('auth.signup')}}">Register</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </nav>        
        {% block content %}
            
        {% endblock content %}
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
    </body>
</html>

marvel_app/templates/site_create.html
<form method = 'POST'>
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset>
            {{ form.name.label }}
            {{ form.name(class = "form-control", placeholder = "Enter Character Name") }}
        </fieldset>
        <fieldset>
            {{  form.description.label }}
            {{ form.description(class = "form-control", placeholder = "Enter a brief description of the character") }}
        </fieldset>
        <fieldset>
            {{  form.movies.label }}
            {{ form.movies(class = "form-control", placeholder = "List the movies character is featured in...") }}
        </fieldset>
        <fieldset>
            {{  form.events.label }}
            {{ form.events(class = "form-control", placeholder = "eg.. Ragnarok, Infinity War, The Blip") }}
        </fieldset>
        <fieldset>
            {{  form.series.label }}
            {{ form.series(class = "form-control", placeholder = "eg.. Infinity Saga, Netflix Show") }}
        </fieldset>
        <fieldset>
            {{  form.powers.label }}
            {{ form.powers(class = "form-control", placeholder = "Enter a brief list of powers...") }}
        </fieldset>
        <fieldset>
            {% for subfield in form.radio %}
                <div class="subfield">
                    {{ subfield }}
                    {{ subfield.label }}
                </div>
            {% endfor %}
        </fieldset>
        <div id="sub_butt">
            {{ form.submit_button(class = "btn btn-danger") }}
        </div>
    </div>
</form>